package it.polimi.ingsw.network;
/**This enum-class is used to handle error-connection. It can identify the status of connection
 * when an error occurs */
public enum StatusNetwork {
    AFTER_ACCEPTION_SOCKET_BEFORE_LOGIN_MESSAGE,
    ARRIVED_LOGIN_MESSAGE,
    AFTER_REQUEST_NUMBER_PLAYER,
    AFTER_SEND_ACCEPT_MESSAGE_WITH_NUMBER_PLAYER, AFTER_JOIN_LOBBY_OLD_PLAYER,
    AFTER_SEND_ACCEPT_MESSAGE,
    SEND_MESSSGE_GAME_IS_NOT_AVAILABLE_FOR_RELOAD,
    SEND_ERROR_MESSAGE_CLIENT_NEED_TO_BE_CLOSED,
    AFTER_SEND_INVALID_NAME_MESSAGE,
    NEW_GAME_IS_STARTING,
    IN_GAME, END_OF_THE_GAME;
}
